project:
  type: website
  output-dir: docs

website:
  title: "Sanchita Kamath | UX Researcher"
  favicon: img/favicon.png
  navbar:
    logo: img/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Work ğŸš€
      - href: research.qmd
        text: Research ğŸ”
      - href: writing.qmd
        text: Writings ğŸ““
      - href: about.qmd
        text: About
      - href: cv.qmd
        text: Resume
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/sanchitakamath/
      - icon: envelope
        href: "mailto:mail.kamath.sanchita@gmail.com"
      - icon: github
        href: https://github.com/yourgithubusername

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    include-in-header:
      text: |
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;500;600;700&family=Roboto:wght@300;400;500;700&family=Open+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
    include-after-body:
      text: |
        <script src="animations.js"></script>
        <script src="hover-enhancements.js"></script>